# version: 2
# jobs:
#   build:
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}-{{ .Branch }}
#       - run:
#           name: Install packages
#           command: yarn install --pure-lockfile
#       - run:
#           name: Run tests
#           command: yarn test
#       - run:
#           name: Build project
#           command: yarn build
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}-{{ .Branch }}
#           paths:
#             - node_modules

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test